// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz3LYh3zbZbUgc1jlFU5tm3AEaYE5_0VQ',
    appId: '1:74313558547:web:8990e076971a4372dc6de6',
    messagingSenderId: '74313558547',
    projectId: 'citas-odontologicas-d7063',
    authDomain: 'citas-odontologicas-d7063.firebaseapp.com',
    storageBucket: 'citas-odontologicas-d7063.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVnG2ajGWyNABvKdrcxZ0wu8L1q5iK4jE',
    appId: '1:74313558547:android:2447ff2b9ee14b2bdc6de6',
    messagingSenderId: '74313558547',
    projectId: 'citas-odontologicas-d7063',
    storageBucket: 'citas-odontologicas-d7063.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWBZpdWkNeoRyFnYJF75NykO8nPKU5-e8',
    appId: '1:74313558547:ios:79b5b9d3a73e00dcdc6de6',
    messagingSenderId: '74313558547',
    projectId: 'citas-odontologicas-d7063',
    storageBucket: 'citas-odontologicas-d7063.firebasestorage.app',
    iosBundleId: 'com.example.mydentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWBZpdWkNeoRyFnYJF75NykO8nPKU5-e8',
    appId: '1:74313558547:ios:79b5b9d3a73e00dcdc6de6',
    messagingSenderId: '74313558547',
    projectId: 'citas-odontologicas-d7063',
    storageBucket: 'citas-odontologicas-d7063.firebasestorage.app',
    iosBundleId: 'com.example.mydentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz3LYh3zbZbUgc1jlFU5tm3AEaYE5_0VQ',
    appId: '1:74313558547:web:f6f03f3720a955fedc6de6',
    messagingSenderId: '74313558547',
    projectId: 'citas-odontologicas-d7063',
    authDomain: 'citas-odontologicas-d7063.firebaseapp.com',
    storageBucket: 'citas-odontologicas-d7063.firebasestorage.app',
  );
}
